name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: mail
          POSTGRES_USER: mail
          POSTGRES_PASSWORD: mailpass
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U mail" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install API deps
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/api/requirements.txt
      - name: Run API tests
        env:
          DATABASE_URL: postgresql+psycopg2://mail:mailpass@localhost:5432/mail
        run: |
          cd apps/api
          alembic upgrade head
          pytest -q
